PaulsAutoParts/Controllers/Shopping/CartController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using PaulsAutoParts.Common;
using PaulsAutoParts.EntityLayer;
using PaulsAutoParts.AppClasses;
using PaulsAutoParts.ViewModelLayer;

namespace PaulsAutoParts.Controllers
{
  public class CartController : AppController
  {
    #region Constructor
    public CartController(AppSession session,
             IRepository<Product, ProductSearch> repo,
             IRepository<VehicleType, VehicleTypeSearch> vrepo,
             IRepository<PromoCode, PromoCodeSearch> prepo) : base(session)
    {
      _repo = repo;
      _vehicleRepo = vrepo;
      _promoRepo = prepo;
    }
    #endregion

    #region Private Fields      
    private readonly IRepository<Product, ProductSearch> _repo;
    private readonly IRepository<VehicleType, VehicleTypeSearch> _vehicleRepo;
    private readonly IRepository<PromoCode, PromoCodeSearch> _promoRepo;
    #endregion

    [HttpGet]
    public IActionResult Index()
    {
      // Set Cart from Session
      ShoppingViewModel vm = new(_repo, _vehicleRepo, UserSession.Cart);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Set Cart into View Model
      vm.Cart = UserSession.Cart;

      // See if the cart has expired
      if (vm.Cart.DateExpires < DateTime.Now) {
        // Expire the cart
        vm.ExpireCart(vm.Cart);

        // Set cart into session
        UserSession.Cart = vm.Cart;
      }

      return View(vm);
    }

    [HttpPost]
    public IActionResult UpdateQuantity(ShoppingCartItem item)
    {
      // Set Cart from Session
      ShoppingViewModel vm = new(_repo, _vehicleRepo, UserSession.Cart);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Update item
      vm.UpdateQuantity(item);

      // Set cart into session
      UserSession.Cart = vm.Cart;

      // Must clear model state to have new quantity appear
      ModelState.Clear();

      return View("Index", vm);
    }

    [HttpPost]
    public IActionResult ApplyPromoCode(ShoppingViewModel vm)
    {
      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Assign Repositories
      vm.Repository = _repo;
      vm.VehicleRepository = _vehicleRepo;
      vm.PromoCodeRepository = _promoRepo;

      // Set Cart from Session
      vm.Cart = UserSession.Cart;

      // Apply Promo Code if it exists, and another one has not been applied
      vm.ApplyPromoCode();

      // Set cart into session
      UserSession.Cart = vm.Cart;

      // Must clear model state to have new values appear
      ModelState.Clear();

      return View("Index", vm);
    }

  }
}

PaulsAutoParts/Controllers/Shopping/CheckOutController.cs
using Microsoft.AspNetCore.Mvc;
using PaulsAutoParts.Common;
using PaulsAutoParts.EntityLayer;
using PaulsAutoParts.AppClasses;
using PaulsAutoParts.ViewModelLayer;

namespace PaulsAutoParts.Controllers
{
  public class CheckOutController : AppController
  {
    #region Constructor
    public CheckOutController(AppSession session,
             IRepository<CustomerPayment, CustomerPaymentSearch> repository,
             IRepository<OrderHeader, OrderHeaderSearch> ohRepository,
             IRepository<OrderDetail, OrderDetailSearch> odRepository) : base(session)
    {
      _repo = repository;
      _headerRepo = ohRepository;
      _detailRepo = odRepository;
    }
    #endregion

    #region Private Fields      
    private readonly IRepository<CustomerPayment, CustomerPaymentSearch> _repo;
    private readonly IRepository<OrderHeader, OrderHeaderSearch> _headerRepo;
    private readonly IRepository<OrderDetail, OrderDetailSearch> _detailRepo;
    #endregion

    [HttpGet]
    public IActionResult Index()
    {
      // Set Cart from Session
      CheckOutViewModel vm = new(_repo, _headerRepo, _detailRepo, UserSession.Cart);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Set Customer Name into CC information
      vm.CustomerCreditCard.NameOnCard = vm.CustomerName;

      // Load Drop-Downs
      vm.LoadCardTypes();
      vm.LoadMonths();
      vm.LoadYears();

      return View(vm);
    }

    [HttpPost]
    public IActionResult ProcessCreditCard(CheckOutViewModel vm)
    {
      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Set Repositories into View Model
      vm.Repository = _repo;
      vm.OrderHeaderRepository = _headerRepo;
      vm.OrderDetailRepository = _detailRepo;

      // Set cart into view model
      vm.Cart = UserSession.Cart;

      // Process the credit card information
      vm.ProcessCreditCard(UserSession.CustomerId.Value);

      // Clear Shopping Cart
      vm.ExpireCart(vm.Cart);

      // Set cart back into session
      UserSession.Cart = vm.Cart;

      return View("Receipt", vm);
    }
  }
}

PaulsAutoParts/Views/Cart/Index.cshtml
@using PaulsAutoParts.EntityLayer
@model PaulsAutoParts.ViewModelLayer.ShoppingViewModel

@{
    ViewData["Title"] = "Your Cart";
}

<span class="d-none" id="cartExpires">@Model.Cart.DateExpires.ToString("yyyy-MM-dd hh:mm:ss tt")</span>

<div class="text-center">
    <h1 class="display-4">Your Shopping Cart</h1>
    @if (Model.Cart.Items != null && Model.Cart.Items.Count > 0)
    {
        <p><strong>NOTE: </strong><span id="cartExpirationMsg">@Model.Cart.CartExpirationMessage</span></p>
    }
</div>

@if (Model.Cart.Items == null || Model.Cart.Items.Count == 0)
{
    <div class="text-center">
        <p>You Have Not Added Any Items To Your Shopping Cart</p>
    </div>
}
else
{
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Quantity</th>
                <th>Product Name</th>
                <th class="text-right">Unit Price</th>
                <th class="text-right">Total Price</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ShoppingCartItem item in Model.Cart.Items)
            {
                <tr id="@item.ProductId">
                    <td>
                        <form method="post" asp-action="UpdateQuantity">
                            <div class="row">
                                <div class="col">
                                    <input asp-for="@item.Quantity" class="form-control" />
                                    <input class="d-none" type="hidden" asp-for="@item.ProductId" />
                                </div>
                                <div class="col">
                                    <button class="btn btn-info">Update</button>
                                </div>
                            </div>
                        </form>
                    </td>
                    <td>@Html.DisplayFor(m => item.ProductName)</td>
                    <td class="text-right">@Html.DisplayFor(m => item.Price)</td>
                    <td class="text-right">@Html.DisplayFor(m => item.TotalPrice)</td>
                    <td>
                        <a class="btn btn-danger" onclick="pageController.deleteCartItem(@item.ProductId)">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td class="text-right"><strong>Total</strong></td>
                <td class="text-right"><strong>@Html.DisplayFor(Model => Model.Cart.TotalCart)</strong></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td class="text-right"><strong>Promotional Code</strong></td>
                <td class="text-right">
                    <form method="post" asp-action="ApplyPromoCode">
                        <div class="form-group">
                            @if (string.IsNullOrEmpty(Model.Cart.PromotionCode.PromotionalCode))
                            {
                                <label asp-for="PromoCodeToApply" class="control-label"></label>
                                <input required asp-for="PromoCodeToApply" class="form-control" />
                            }
                            else
                            {
                                <label class="control-label">Promotional Code Applied</label>
                                <input readonly asp-for="Cart.PromotionCode.PromotionalCode" class="form-control" />
                            }
                        </div>
                        @if (string.IsNullOrEmpty(Model.Cart.PromotionCode.PromotionalCode))
                        {
                            <div class="form-group">
                                <button class="btn btn-success">Apply Promo Code</button>
                            </div>
                        }
                    </form>
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="row">
        <div class="col mr-auto text-right">
            <a class="btn btn-primary" asp-controller="CheckOut" asp-action="Index">Check Out</a>
        </div>
    </div>
}

<div class="row">
    <div class="col text-center">
        <span><strong>@Model.Message</strong></span>
    </div>
</div>

@section Scripts {
<script src="~/js/cart/cart.js"></script>
<script src="~/js/cart/expiry.js"></script>
<script src="~/js/car/pageControler.js"></script>
}