PaulsAutoParts/Controllers/Customer/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using PaulsAutoParts.Common;
using PaulsAutoParts.EntityLayer;
using PaulsAutoParts.AppClasses;
using PaulsAutoParts.ViewModelLayer;

namespace PaulsAutoParts.Controllers
{
  public class CustomerController : AppController
  {
    #region Constructor
    /// <summary>
    /// Constructor for CustomerController class
    /// </summary>
    public CustomerController(AppSession session,
           IRepository<Customer, CustomerSearch> repo) : base(session)
    {
      _repo = repo;
    }
    #endregion

    #region Private Fields
    private readonly IRepository<Customer, CustomerSearch> _repo;
    #endregion

    #region CustomerIndex Methods
    /// <summary>
    /// Executes when browser issues a Get request for /Customer and 
    /// directs to the Index view
    /// </summary>
    /// <returns>An ActionResult that contains an instance of CustomerViewModel</returns>
    public ActionResult CustomerIndex()
    {
      // Create view model and pass in repository
      CustomerViewModel vm = new(_repo);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Call method to load current customer data
      vm.Get(UserSession.CustomerId.Value);

      return View(vm);
    }

    /// <summary>
    /// Handles the browser Post request for Customer form
    /// </summary>
    /// <param name="vm">A CustomerViewModel instance for the entry</param>
    /// <returns>An ActionResult that either navigates to the index or stays on this view and displays errors</returns>
    [HttpPost]
    public ActionResult CustomerIndex(CustomerViewModel vm)
    {
      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Assign Repository to View Model
      vm.Repository = _repo;

      if (ModelState.IsValid) {
        // Save the Data
        vm.Save();

        vm.Message = "Your Information Has Been Updated";

        // Redisplay Data
        return View("CustomerIndex", vm);
      }
      else {
        vm.IsDetailVisible = true;

        return View(vm);
      }
    }
    #endregion
  }
}

PaulsAutoParts/Controllers/Maintenance/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using PaulsAutoParts.Common;
using PaulsAutoParts.EntityLayer;
using PaulsAutoParts.AppClasses;
using PaulsAutoParts.ViewModelLayer;

namespace PaulsAutoParts.Controllers
{
  public class ProductController : AppController
  {
    #region Constructor
    /// <summary>
    /// Constructor for ProductController class
    /// </summary>
    public ProductController(AppSession session,
           IRepository<Product, ProductSearch> repo) : base(session)
    {
      _repo = repo;
    }
    #endregion

    #region Private Fields
    private readonly IRepository<Product, ProductSearch> _repo;
    #endregion

    #region ProductIndex Methods
    /// <summary>
    /// Executes when browser issues a Get request for /Product and 
    /// directs to the Index view
    /// </summary>
    /// <returns>An ActionResult that contains an instance of ProductViewModel</returns>
    public ActionResult ProductIndex()
    {
      // Create view model and pass in repository
      ProductViewModel vm = new(_repo);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Call method to load data
      vm.Get();

      return View(vm);
    }

    /// <summary>
    /// Handles the browser Post request for Product form
    /// </summary>
    /// <param name="vm">A ProductViewModel instance for the entry</param>
    /// <returns>An ActionResult that either navigates to the index or stays on this view and displays errors</returns>
    [HttpPost]
    public ActionResult ProductIndex(ProductViewModel vm)
    {
      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Assign Repository to View Model
      vm.Repository = _repo;

      if (ModelState.IsValid) {
        // Save the Data
        vm.Save();

        // Redirect back to list
        return RedirectToAction("ProductIndex");
      }
      else {
        vm.IsDetailVisible = true;

        return View(vm);
      }
    }
    #endregion

    #region Edit Method
    [HttpGet]
    public IActionResult Edit(int id)
    {
      // Create view model and pass in repository
      ProductViewModel vm = new(_repo);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Call method to load a single record
      vm.Get(id);

      return View("ProductIndex", vm);
    }
    #endregion

    #region Search Method
    [HttpGet]
    public IActionResult Search(ProductViewModel vm)
    {
      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Assign Repository to View Model
      vm.Repository = _repo;

      // Call method to search for data
      vm.Search();

      return View("ProductIndex", vm);
    }
    #endregion

    #region Add Method
    [HttpGet]
    public IActionResult Add()
    {
      // Create view model and pass in repository
      ProductViewModel vm = new(_repo)
      {
        IsDetailVisible = true
      };

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Call method to create an empty entity to add
      vm.CreateEmptyEntity();

      return View("ProductIndex", vm);
    }
    #endregion

    #region Delete Method
    [HttpGet]
    public IActionResult Delete(int id)
    {
      // Create view model and pass in repository
      ProductViewModel vm = new(_repo);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Call method to delete a record
      vm.Delete(id);

      return RedirectToAction("ProductIndex");
    }
    #endregion
  }
}

PaulsAutoParts/Controllers/Shopping/CartController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using PaulsAutoParts.Common;
using PaulsAutoParts.EntityLayer;
using PaulsAutoParts.AppClasses;
using PaulsAutoParts.ViewModelLayer;

namespace PaulsAutoParts.Controllers
{
  public class CartController : AppController
  {
    #region Constructor
    public CartController(AppSession session,
             IRepository<Product, ProductSearch> repo,
             IRepository<VehicleType, VehicleTypeSearch> vrepo,
             IRepository<PromoCode, PromoCodeSearch> prepo) : base(session)
    {
      _repo = repo;
      _vehicleRepo = vrepo;
      _promoRepo = prepo;
    }
    #endregion

    #region Private Fields      
    private readonly IRepository<Product, ProductSearch> _repo;
    private readonly IRepository<VehicleType, VehicleTypeSearch> _vehicleRepo;
    private readonly IRepository<PromoCode, PromoCodeSearch> _promoRepo;
    #endregion

    [HttpGet]
    public IActionResult Index()
    {
      // Set Cart from Session
      ShoppingViewModel vm = new(_repo, _vehicleRepo, UserSession.Cart);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Set Cart into View Model
      vm.Cart = UserSession.Cart;

      // See if the cart has expired
      if (vm.Cart.DateExpires < DateTime.Now) {
        // Expire the cart
        vm.ExpireCart(vm.Cart);

        // Set cart into session
        UserSession.Cart = vm.Cart;
      }

      return View(vm);
    }

    [HttpPost]
    public IActionResult UpdateQuantity(ShoppingCartItem item)
    {
      // Set Cart from Session
      ShoppingViewModel vm = new(_repo, _vehicleRepo, UserSession.Cart);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Update item
      vm.UpdateQuantity(item);

      // Set cart into session
      UserSession.Cart = vm.Cart;

      // Must clear model state to have new quantity appear
      ModelState.Clear();

      return View("Index", vm);
    }

    [HttpPost]
    public IActionResult ApplyPromoCode(ShoppingViewModel vm)
    {
      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Assign Repositories
      vm.Repository = _repo;
      vm.VehicleRepository = _vehicleRepo;
      vm.PromoCodeRepository = _promoRepo;

      // Set Cart from Session
      vm.Cart = UserSession.Cart;

      // Apply Promo Code if it exists, and another one has not been applied
      vm.ApplyPromoCode();

      // Set cart into session
      UserSession.Cart = vm.Cart;

      // Must clear model state to have new values appear
      ModelState.Clear();

      return View("Index", vm);
    }

  }
}

PaulsAutoParts/Controllers/Shopping/ShoppingController.cs
using Microsoft.AspNetCore.Mvc;
using PaulsAutoParts.Common;
using PaulsAutoParts.EntityLayer;
using PaulsAutoParts.AppClasses;
using PaulsAutoParts.ViewModelLayer;

namespace PaulsAutoParts.Controllers
{
  public class ShoppingController : AppController
  {
    #region Constructor
    public ShoppingController(AppSession session,
             IRepository<Product, ProductSearch> repo,
             IRepository<VehicleType, VehicleTypeSearch> vrepo) : base(session)
    {
      _repo = repo;
      _vehicleRepo = vrepo;
    }
    #endregion

    #region Private Fields      
    private readonly IRepository<Product, ProductSearch> _repo;
    private readonly IRepository<VehicleType, VehicleTypeSearch> _vehicleRepo;
    #endregion

    #region Index Method
    [HttpGet]
    public IActionResult Index()
    {
      // Set Cart from Session
      ShoppingViewModel vm = new(_repo, _vehicleRepo, UserSession.Cart);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      return View(vm);
    }
    #endregion

    #region ChangeYearMakeModel Method
    [HttpGet]
    public IActionResult ChangeYearMakeModel(ShoppingViewModel vm)
    {
      // Set values for changing year/make/model
      SetYearMakeModel(vm);

      return View("Index", vm);
    }
    #endregion

    #region SearchYearMakeModel Method
    [HttpGet]
    public IActionResult SearchYearMakeModel(ShoppingViewModel vm)
    {
      // Set values for searching
      SetYearMakeModel(vm);

      // Search for Products
      vm.Search();

      return View("Index", vm);
    }
    #endregion

    #region SetYearMakeModel Method
    protected void SetYearMakeModel(ShoppingViewModel vm)
    {
      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Assign Repositories
      vm.Repository = _repo;
      vm.VehicleRepository = _vehicleRepo;

      // Reset Search Entity
      vm.SearchEntity.ProductName = null;

      // Set Cart from Session
      vm.Cart = UserSession.Cart;

      // Load Drop-Downs
      vm.GetCategories();
      vm.LoadYearsMakesModels();

      // Store last product search
      UserSession.LastProductSearch = vm.SearchEntity;
    }
    #endregion

    #region SearchNameCategory Method
    [HttpGet]
    public IActionResult SearchNameCategory(ShoppingViewModel vm)
    {
      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Assign Repositories
      vm.Repository = _repo;
      vm.VehicleRepository = _vehicleRepo;

      // Reset Search Entity
      vm.SearchEntity.Year = null;
      vm.SearchEntity.Make = null;
      vm.SearchEntity.Model = null;

      // Set Cart from Session
      vm.Cart = UserSession.Cart;

      // Load Drop-Downs
      vm.GetYears();
      vm.GetCategories();

      // Store last product search
      UserSession.LastProductSearch = vm.SearchEntity;

      // Search for Products
      vm.Search();

      return View("Index", vm);
    }
    #endregion

    #region Add Method
    [HttpGet]
    public IActionResult Add(int id)
    {
      // Set Cart from Session
      ShoppingViewModel vm = new(_repo, _vehicleRepo, UserSession.Cart);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Restore last product search
      vm.SearchEntity = UserSession.LastProductSearch;

      // Add item to cart
      vm.AddToCart(id, UserSession.CustomerId.Value);

      // Set cart into session
      UserSession.Cart = vm.Cart;

      // Load Drop-Downs
      vm.LoadYearsMakesModels();
      vm.GetCategories();

      // Search for Products
      vm.Search();

      return View("Index", vm);
    }
    #endregion

    #region Remove Method
    [HttpGet]
    public IActionResult Remove(int id)
    {
      // Set Cart from Session
      ShoppingViewModel vm = new(_repo, _vehicleRepo, UserSession.Cart);

      // Set "Common" View Model Properties from Session
      base.SetViewModelFromSession(vm, UserSession);

      // Restore last product search
      vm.SearchEntity = UserSession.LastProductSearch;

      // Remove item to cart
      vm.RemoveFromCart(vm.Cart, id, UserSession.CustomerId.Value);

      // Set cart into session
      UserSession.Cart = vm.Cart;

      // Load Drop-Downs
      vm.LoadYearsMakesModels();
      vm.GetCategories();

      // Search for Products
      vm.Search();

      return View("Index", vm);
    }
    #endregion
  }
}

PaulsAutoParts/Views/Shared/_CustomerOrders.cshtml
@using PaulsAutoParts.EntityLayer
@model PaulsAutoParts.ViewModelLayer.CustomerPaymentViewModel

<tr>
  <td></td>
  <td colspan="2">
    <p><strong>Order Date</strong>: @Model.OrderInformation.OrderDate.Value.ToShortDateString()</p>
  </td>
  <td colspan="2">
    <p><strong>Promotional Code Used</strong>: @Model.OrderInformation.PromotionalCode</p>
  </td>
  <td></td>
</tr>
<tr>
  <td></td>
  <td colspan="4">
    <table class="table table-bordered table-hover table-striped">
      <thead>
        <tr>
          <th>Product ID</th>
          <th>Product Name</th>
          <th>Quantity</th>
          <th>Paid</th>
        </tr>
      </thead>
      <tbody>
        @foreach (OrderDetail detail in Model.OrderDetails) {
          <tr>
            <td>@Html.DisplayFor(m => detail.ProductId)</td>
            <td>@Html.DisplayFor(m => detail.ProductName)</td>
            <td>@Html.DisplayFor(m => detail.Quantity)</td>
            <td>@Html.DisplayFor(m => detail.Price)</td>
          </tr>
        }
      </tbody>
    </table>
  </td>
  <td></td>
</tr>

PaulsAutoParts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/all.css" />

    @RenderSection("HeadStyles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Paul's Auto Parts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Shopping" asp-action="Index">Shop</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="adminDropDown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                            <div class="dropdown-menu" aria-labelledby="adminDropDown">
                                <a asp-action="ProductIndex"
                                   data-waitmsg="Please wait while loading Products..."
                                   asp-controller="Product" class="dropdown-item"
                                   onclick="mainController.pleaseWait(this)">
                                    Products
                                </a>
                                <div class="dropdown-divider"></div>

                                <a asp-action="CustomerMaintIndex"
                                   asp-controller="CustomerMaint" class="dropdown-item">
                                    Customers / Orders
                                </a>

                                <div class="dropdown-divider"></div>

                                <a asp-action="PromoCodeIndex"
                                   asp-controller="PromoCode" class="dropdown-item">
                                    Promotional Codes
                                </a>

                                <a asp-action="VehicleTypeIndex"
                                   asp-controller="VehicleType" class="dropdown-item"
                                   data-waitmsg="Please wait while loading Vehicles..."
                                   onclick="mainController.pleaseWait(this)">
                                    Vehicle Types
                                </a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-2 justify-content-end">
                        <li class="nav-item dropdown bg-dark text-light p-1">
                            <a id = "itemsInCart" class="text-light" asp-action="Index" asp-controller="Cart">@ViewData["ItemsInCart"] Items in Cart</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-2 mr-auto justify-content-end">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="custDropDown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @ViewData["CustomerName"]
                            </a>
                            <div class="dropdown-menu" aria-labelledby="custDropDown">
                                <a asp-action="CustomerIndex"
                                   asp-controller="Customer" class="dropdown-item">
                                    My Information
                                </a>
                                <a asp-action="CustomerPaymentIndex"
                                   asp-controller="CustomerPayment" class="dropdown-item">
                                    My Orders/Payments
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div id="pleaseWait" class="pleaseWaitMessage d-none">
            <h4>
                <span id="theWaitMessage">
                    Please wait while loading
                </span>
                &nbsp;
                <i class="fas fa-cog fa-spin" style="z-index: 99">
                </i>
            </h4>
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>